<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Login_Data_TS_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>ae16ddb9-85b9-4258-80d3-bae793899db2</testSuiteGuid>
   <testCaseLink>
      <guid>4317fdf5-cf30-45da-81a4-6271c4da17d0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login_Data_TC_1/Login_Data_TC_1</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>20c25a00-003d-4234-970b-1e5501a4bc40</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Login_Data_Cura/Login_Data_Cura</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>20c25a00-003d-4234-970b-1e5501a4bc40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>e7920367-1e84-4f1d-ba35-cbe6da885e46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>20c25a00-003d-4234-970b-1e5501a4bc40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d7ac722a-9517-4c7b-aba6-0d4087fc2f6d</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
