<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Masuk</name>
   <tag></tag>
   <elementGuidId>2de1a327-bd99-4baf-935f-1607e873bd5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.sx2jih0.zcydq85y.zcydq8p.zcydq85a.zcydq84u.zcydq8y.zcydq8x.zcydq85.zcydq8g2.zcydq84.zcydq8h._97fi8d0._97fi8d5</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div[4]/div/div/div/div[2]/div[2]/div/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation</name>
      <type>Main</type>
      <value>Login</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Masuk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sx2jih0 zcydq85y zcydq8p zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://myjobstreet.jobstreet.co.id/home/login.php?site=id</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;r993om0 _18qlyvc14 _18qlyvc17&quot;]/div[@class=&quot;sx2jih0&quot;]/div[@class=&quot;sx2jih0 zcydq856 zcydq8em zcydq8ea zcydq8f6&quot;]/div[@class=&quot;sx2jih0 zcydq856 zcydq8f6 zcydq8em zcydq8p y759cs0 _18qlyvc14 _18qlyvc17 zcydq832 zcydq835&quot;]/div[@class=&quot;sx2jih0 zcydq8p zcydq8v _1xiw5030&quot;]/div[@class=&quot;sx2jih0 zcydq896 zcydq886 zcydq856 zcydq8ea zcydq8eu zcydq8p zcydq8n zcydq85b y759cs0 y759cs2 _18qlyvc14 _18qlyvc17 zcydq832 zcydq835&quot;]/div[@class=&quot;sx2jih0 zcydq8ea zcydq84q zcydq857 zcydq8n&quot;]/div[@class=&quot;sx2jih0&quot;]/div[@class=&quot;sx2jih0 zcydq8n zcydq856 _136ckug1&quot;]/div[@class=&quot;sx2jih0 zcydq8n zcydq8fi zcydq856 zcydq8ea&quot;]/div[@class=&quot;sx2jih0 _17fduda0 _17fduda5&quot;]/div[@class=&quot;sx2jih0 zcydq8fe zcydq856 zcydq8ey _17fduda25&quot;]/div[@class=&quot;sx2jih0 zcydq8r zcydq8di zcydq8ai zcydq84u zcydq8ei&quot;]/a[@class=&quot;sx2jih0 zcydq85y zcydq8p zcydq85a zcydq84u zcydq8y zcydq8x zcydq85 zcydq8g2 zcydq84 zcydq8h _97fi8d0 _97fi8d5&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div[4]/div/div/div/div[2]/div[2]/div/div/div/div/div/a</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bahasa'])[2]/following::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='English'])[1]/following::a[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untuk perusahaan'])[1]/preceding::a[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://myjobstreet.jobstreet.co.id/home/login.php?site=id')])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a</value>
   </webElementXpaths>
</WebElementEntity>
